version: "3.9"

services:
  postgres:
    image: postgres:14.4
    container_name: postgresql14_4
    volumes:
      - "./dump/:/docker-entrypoint-initdb.d/"
      - "db-data:/var/lib/postgresql/data"
    env_file:
      - ./env/postgres
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4:6
    container_name: pgadmin4
    ports:
      - "5050:80"
    env_file:
      - ./env/pgadmin
    volumes:
      - "pgadmin-data:/var/lib/pgadmin"

volumes:
  db-data:
  pgadmin-data: